added express-rate-limiter
LeoTuet/backend-we-want-to-sleep pull request #29
Opened 2022-02-11 08:09 UTC by marcschwaiger

Using express-rate-limiter we can block e. g. brute force attacks on admin login

2022-02-11 08:11 UTC, marcschwaiger commented
Needs to be reviewed @94726

2022-02-11 08:56 UTC, marcschwaiger commented
Had to remove --silent in order to see the error I had. I recommend keeping the output from npm ci

2022-02-11 09:15 UTC, 94726 requested changes

2022-02-11 09:15 UTC, 94726 commented on src/app.ts
> +app.use("/admin/login", adminLoginLimiter);
Maybe put the middleware use directly into router/index.ts similar to other middleware uses

2022-02-11 09:21 UTC, marcschwaiger commented on src/app.ts
> +app.use("/admin/login", adminLoginLimiter);
Resolved in [moved rate limiter config to its own class](https://github.com/LeoTuet/backend-we-want-to-sleep/pull/29/commits/c53c61c4be3a91d21fc66df9391bf5277657553b)[](https://github.com/LeoTuet/backend-we-want-to-sleep/pull/29/commits/c53c61c4be3a91d21fc66df9391bf5277657553b)

2022-02-11 10:13 UTC, marcschwaiger commented
In order for this to work, the [configuration file patch](https://github.com/LeoTuet/deployment-we-want-to-sleep/pull/4) must be applied

2022-02-12 01:38 UTC, 94726 approved these changes

2022-02-14 19:44 UTC, merged